### ISSUE TITLE
Problema com delay ao digitar/apagar

### ISSUE THREAD

**Issue by AirtonL** [israelss/reactcron#19]
Salve mestre, dando uma olhada na sua aplicação rodando, notei que ao digitar ou apagar mais de um digito "rapidamente" ele tem um delay e não deixa apagar ou adicionar o digito subsequente, precisando esperar algum tempinho para isso, talvez seria legal dar uma olhada nisso. No mais Parabéns, ficou muito bom!!

**Comment by israelss** [comment]
Thank you for the report @AirtonL! :green_heart: 
This bug should be resolved now. :adhesive_bandage: 
Please, [check the app again](https://israelss.github.io/reactcron/), and feel free to open any new issues/PRs. :rocket:
